// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieSolution.Context;

#nullable disable

namespace MovieSolution.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20220724013238_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieSolution.Context.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("IdImbd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("UserScore")
                        .HasColumnType("float");

                    b.Property<bool>("Watched")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "John Wick is on the run after killing a member of the international assassins",
                            Genre = 0,
                            IdImbd = "tt6146586",
                            Name = "John Wick",
                            ReleaseDate = new DateTime(2019, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserScore = 8.9000000000000004,
                            Watched = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins",
                            Genre = 0,
                            IdImbd = "tt4154796",
                            Name = "Avengers: Endgame",
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserScore = 8.4000000000000004,
                            Watched = false
                        },
                        new
                        {
                            Id = 3,
                            Description = "The untold story of one twelve-year-old's dream to become the world's greatest supervillain",
                            Genre = 1,
                            IdImbd = "tt5113044",
                            Name = "Minions: The Rise of Gru",
                            ReleaseDate = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserScore = 6.9000000000000004,
                            Watched = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
